version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    depends_on:
      - rtsp-proxy

  rtsp-proxy:
    image: aler9/rtsp-simple-server
    network_mode: host
    ports:
      - "8554:8554"
      - "8888:8888"
    volumes:
      - ./rtsp-simple-server:/rtsp-simple-server.yml
